#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM busybox:1.36.1-musl AS toolbox

FROM dhi.io/superset:6

COPY --from=toolbox /bin/busybox /usr/local/bin/busybox

USER 0

ENV SUPERSET_HOME=/app/superset_home \
    HOME=/app/superset_home \
    PYTHONPATH=/app/pythonpath

RUN python - <<'PY'
import os

try:
    os.symlink("/usr/local/bin/busybox", "/usr/local/bin/mkdir")
except FileExistsError:
    pass

for cmd in ("grep", "ls", "cat"):
    try:
        os.symlink("/usr/local/bin/busybox", f"/usr/local/bin/{cmd}")
    except FileExistsError:
        pass

paths = ["/app/superset_home", "/app/pythonpath", "/tmp/superset", "/tmp/pythonpath"]
for path in paths:
    os.makedirs(path, exist_ok=True)


def set_group_writable_recursive(root: str) -> None:
    if not os.path.exists(root):
        return

    for current_root, dirs, files in os.walk(root):
        entries = [
            current_root,
            *[os.path.join(current_root, d) for d in dirs],
            *[os.path.join(current_root, f) for f in files],
        ]
        for entry in entries:
            try:
                if os.path.islink(entry):
                    continue
                st = os.stat(entry)
                os.chown(entry, -1, 0)
                mode = st.st_mode
                owner_bits = (mode & 0o700) >> 3
                new_mode = mode | owner_bits
                os.chmod(entry, new_mode)
            except OSError:
                continue


for target in ["/app", "/tmp/superset", "/tmp/pythonpath"]:
    set_group_writable_recursive(target)
PY

USER 1001
